# Site settings
title: Blog personal
email: aldriguz@outlook.com
timezone: America/Lima
description: > # this means to ignore newlines until "baseurl:"
  Blog personal en proceso de desarrollo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aldriguz.github.io" # the base hostname & protocol for your site
twitter_username: aldriguz
github_username:  aldriguz

# Build settings
markdown: kramdown
