# Dependencies
#markdown:         redcarpet
highlighter:      none # pygments # old template has: none

# Main info
site: Blog Personal
url: aldriguz.github.io

# Permalinks
permalink:        pretty
# relative_permalinks: true


# Setup
title: Kevin Alama
description: Software Engineer. Tratando de que este blog tenga forma...
baseurl:          /
tagline:          'A Jekyll theme'
author:
  twitter: #yourusername
  name: 'Kevin Alama'
  avatar:
  email: #youremail
  url: #yoururl

# Social
twitter:
  username: aldriguz
  card: summary
  creator: Kevin Alama

# Pagination
paginate:         5


# Custom vars
version:          2.1.0

# GutHub
github:
  repo:           https://github.com/aldriguz

# Disqus
disqus:
  shortname: aldriguz

# Compress
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

# Sass
sass:
  sass_dir:          _sass
  style:            :compressed

# Plugins
exclude:
  - .jekyll-cache

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Unknown setup
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true